services:
  lowkey-vault:
    container_name: example-lowkey-vault
    image: nagyesta/lowkey-vault:4.1.0@sha256:9385c86f7cbd484157c052ef225603e064a2ea7e390521806d6dd7f986a87563
    ports:
      - "10543:10543"
      - "10544:10544"
    volumes:
      - ./lowkey-vault/import/.gitkeep:/import/.gitkeep
      - ./lowkey-vault/data/keyvault.json.hbs:/data/keyvault.json.hbs
    environment:
      LOWKEY_ARGS: "--server.port=10543 --app.token.port=10544 --LOWKEY_VAULT_NAMES=- --LOWKEY_IMPORT_LOCATION=/data/keyvault.json.hbs"

  mysql:
    container_name: spring-akv-example-mysql
    image: mysql:9.5.0@sha256:569c4128dfa625ac2ac62cdd8af588a3a6a60a049d1a8d8f0fac95880ecdbbe5
    environment:
      MYSQL_ROOT_PASSWORD: NOT_A_SECRET_5b8538b6-2bf1-4d38-94f0-308d4fbb757b
    ports:
      - '23306:3306'